apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kubectl-time-start-pod
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/littlejo/kubectl-time-start-pod/releases/download/v0.1.0/kubectl-time-start-pod_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-time-start-pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-time-start-pod"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/littlejo/kubectl-time-start-pod/releases/download/v0.1.0/kubectl-time-start-pod_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./kubectl-time-start-pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-time-start-pod"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/littlejo/kubectl-time-start-pod/releases/download/v0.1.0/kubectl-time-start-pod_windows_amd64.zip
    sha256: ""
    files:
    - from: "/kubectl-time-start-pod.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-time-start-pod.exe"
  shortDescription: A new plugin
  homepage: https://github.com/littlejo/kubectl-time-start-pod
  caveats: |
    Usage:
      $ kubectl kubectl-time-start-pod

    For additional options:
      $ kubectl kubectl-time-start-pod --help
      or https://github.com/littlejo/kubectl-time-start-pod/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
